id: AD74F4914
title: Prayer for the Long Life of Chökyi Nyima Rinpoche
type: translation
pechas:
- I14D2DA2B
- IE7A04E71
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:34:34.149245
  last_modified_at: 2023-01-04 11:34:34.149252
  collections:
  - Chökyi Nyima Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I14D2DA2B/4198: E50B
  IE7A04E71/86A5: E50B
